name: Release

on:
  push:
    tags:
      - v*

jobs:
  create_release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    needs: create_release

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          [
            "aarch64-macos",
            "x86_64-macos",
            "aarch64-linux",
            "x86_64-linux",
            "aarch64-freebsd",
            "x86_64-freebsd",
          ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - name: Build Executable
        run: zig build-exe src/main.zig -femit-bin=azigmetic-${{ matrix.target }} --strip -O ReleaseSafe -target ${{ matrix.target }}

      - name: Upload Executable
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./azigmetic-${{ matrix.target }}
          asset_name: azigmetic-${{ matrix.target }}
          asset_content_type: application/octet-stream
